In [8]:
#Set the initial population to 100
N0=100
#Set the growth rate to 0.4
rate=0.4

#Import numpy to use numpy package
import numpy as np
#Generate an array of time points from 0 to 10, in 0.2 increments 
t=np.arange(0,10.2,0.2)
#Calculate the population size of the colony at time point t 
population_size = N0 * np.exp(rate*t)
#Add noise to population size
population_size_noise = np.random.normal(0,250,len(population_size)) + population_size
#Define range rate to range from 0 to 1, in 0.1 increments 
range_rate=np.arange(0,1.1,0.1)

#Define a function called squared_error to take predicted_data and observed_data
def squared_error(predicted_data,observed_data):
    #The difference between our predicted data and observed data
    residual = predicted_data-observed_data
    #Use the residual to calculate mean squared error
    mse = (1/len(residual)) * np.sum((residual)**2)
    #Return the result
    return mse

#Initialize a list to store our results
mse = []
#Loop through each range_rate
for i in range_rate:
    #Calculate predicted_data at each range_rate
    predicted_data = N0 * np.exp(i*t)
    #Call function to calculate error using predicted_data and population_size_noise
    error = squared_error(predicted_data, population_size_noise)
    #Input each error result into the mse list 
    mse.append(error)

#Find the index of the minimum value in mse
idx_min_mse = np.argmin(mse)
#Use the index of the min value in mse to obtain the corresponding rate
#The arrays are the same size, and generated inorder when iterating over range_rates
best_fit = range_rate[idx_min_mse]

#Print the output best_fit
print('We predict the rate of growth of this bacterial population to be',best_fit)
    


We predict the rate of growth of this bacterial population to be 0.4


In [13]:
mse = (1/100) * np.sum((residual)**2)
mse

11.018077302529669

In [20]:
population_size

array([ 100.        ,  108.32870677,  117.3510871 ,  127.12491503,
        137.71277643,  149.18246976,  161.60744022,  175.06725003,
        189.64808793,  205.44332106,  222.55409285,  241.08997064,
        261.16964734,  282.92170144,  306.48542033,  332.01169227,
        359.66397256,  389.61933018,  422.0695817 ,  457.22251951,
        495.30324244,  536.55559711,  581.24373944,  629.6538261 ,
        682.09584693,  738.90560989,  800.44689143,  867.11376585,
        939.33312874, 1017.56743061, 1102.31763806, 1194.12644178,
       1293.58173155, 1401.32036077, 1518.0322245 , 1644.46467711,
       1781.42731796, 1929.79717555, 2090.52432351, 2264.63796432,
       2453.25301971, 2657.57726999, 2878.91908792, 3118.69581683,
       3378.44284638, 3659.82344437, 3964.63940726, 4294.84259788,
       4652.54744398, 5040.04447781, 5459.81500331])

In [4]:
np.random.normal(0,250,len(population_size))

array([ 211.60658637,   26.89544736, -495.48156432,   -3.74304325,
        -31.45862385,  -25.96138311, -327.62785475, -367.59673752,
         -4.31104413,  151.67542379,  455.13677563,  219.32343381,
       -382.24950235,  -27.60090402,  222.03534237,   53.27244236,
        301.96344447,  171.94310492,   12.52053566, -385.86850328,
        -25.97878669, -278.11372849,   30.29198919,  399.44037772,
         45.33991549, -288.51919566,  154.06256731,  -19.12908102,
         -7.87342503,  226.76697679, -175.24784626,    6.77450459,
       -129.59450834,  176.45785257, -137.16640812,    7.3258602 ,
        -20.8715289 ,   74.39746142, -424.06959993, -215.2945636 ,
         87.3731089 ,  162.80250092,  335.35329973,  -14.42109792,
        -17.8461867 , -182.51186135, -302.96240415,  400.28940914,
        187.16940211,  146.28582002,  -96.4891337 ])

In [27]:
population_size_noise

array([ 126.92912389,  135.25783066,  144.28021099,  154.05403892,
        164.64190033,  176.11159366,  188.53656411,  201.99637392,
        216.57721182,  232.37244496,  249.48321674,  268.01909453,
        288.09877124,  309.85082533,  333.41454422,  358.94081617,
        386.59309645,  416.54845407,  448.99870559,  484.15164341,
        522.23236633,  563.48472101,  608.17286333,  656.58295   ,
        709.02497082,  765.83473379,  827.37601532,  894.04288974,
        966.26225264, 1044.4965545 , 1129.24676196, 1221.05556568,
       1320.51085545, 1428.24948467, 1544.96134839, 1671.393801  ,
       1808.35644185, 1956.72629944, 2117.4534474 , 2291.56708821,
       2480.1821436 , 2684.50639388, 2905.84821182, 3145.62494072,
       3405.37197028, 3686.75256826, 3991.56853115, 4321.77172177,
       4679.47656787, 5066.9736017 , 5486.74412721])

In [31]:
range_rate=np.arange(0,1.1,0.1)

In [32]:
range_rate

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [50]:
def squared_error(s):
    residual = population_size_noise - population_size
    mse = (1/100) * np.sum((residual)**2)
    return mse

In [17]:
residual = population_size - population_size_noise
residual 

array([-4.6480182, -4.6480182, -4.6480182, -4.6480182, -4.6480182,
       -4.6480182, -4.6480182, -4.6480182, -4.6480182, -4.6480182,
       -4.6480182, -4.6480182, -4.6480182, -4.6480182, -4.6480182,
       -4.6480182, -4.6480182, -4.6480182, -4.6480182, -4.6480182,
       -4.6480182, -4.6480182, -4.6480182, -4.6480182, -4.6480182,
       -4.6480182, -4.6480182, -4.6480182, -4.6480182, -4.6480182,
       -4.6480182, -4.6480182, -4.6480182, -4.6480182, -4.6480182,
       -4.6480182, -4.6480182, -4.6480182, -4.6480182, -4.6480182,
       -4.6480182, -4.6480182, -4.6480182, -4.6480182, -4.6480182,
       -4.6480182, -4.6480182, -4.6480182, -4.6480182, -4.6480182,
       -4.6480182])

In [7]:
np.sum((residual)**2)

NameError: name 'residual' is not defined

In [4]:
(1/100) * np.sum((residual)**2)

NameError: name 'np' is not defined

In [5]:
hello

NameError: name 'hello' is not defined

In [1]:
type(mse)

NameError: name 'mse' is not defined

In [16]:
prediction = N0 * np.exp(range_rate*t)

ValueError: operands could not be broadcast together with shapes (11,) (51,) 

In [18]:
np.outer(range_rate*t)

ValueError: operands could not be broadcast together with shapes (11,) (51,) 

In [19]:
np.outer(range_rate,t)

array([[ 0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,
         0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,
         0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,
         0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,
         0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,
         0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ],
       [ 0.  ,  0.02,  0.04,  0.06,  0.08,  0.1 ,  0.12,  0.14,  0.16,
         0.18,  0.2 ,  0.22,  0.24,  0.26,  0.28,  0.3 ,  0.32,  0.34,
         0.36,  0.38,  0.4 ,  0.42,  0.44,  0.46,  0.48,  0.5 ,  0.52,
         0.54,  0.56,  0.58,  0.6 ,  0.62,  0.64,  0.66,  0.68,  0.7 ,
         0.72,  0.74,  0.76,  0.78,  0.8 ,  0.82,  0.84,  0.86,  0.88,
         0.9 ,  0.92,  0.94,  0.96,  0.98,  1.  ],
       [ 0.  ,  0.04,  0.08,  0.12,  0.16,  0.2 ,  0.24,  0.28,  0.32,
         0.36,  0.4 ,  0.44,  0.48,  0.52,  0.56,  0.6 ,  0.64,  0.68,
         0.72,  0.76,  0.8 ,  0.84,  0.88,  0.

In [22]:
predicted_data = N0 * np.exp(np.outer(range_rate,t))
predicted_data

array([[1.00000000e+02, 1.00000000e+02, 1.00000000e+02, 1.00000000e+02,
        1.00000000e+02, 1.00000000e+02, 1.00000000e+02, 1.00000000e+02,
        1.00000000e+02, 1.00000000e+02, 1.00000000e+02, 1.00000000e+02,
        1.00000000e+02, 1.00000000e+02, 1.00000000e+02, 1.00000000e+02,
        1.00000000e+02, 1.00000000e+02, 1.00000000e+02, 1.00000000e+02,
        1.00000000e+02, 1.00000000e+02, 1.00000000e+02, 1.00000000e+02,
        1.00000000e+02, 1.00000000e+02, 1.00000000e+02, 1.00000000e+02,
        1.00000000e+02, 1.00000000e+02, 1.00000000e+02, 1.00000000e+02,
        1.00000000e+02, 1.00000000e+02, 1.00000000e+02, 1.00000000e+02,
        1.00000000e+02, 1.00000000e+02, 1.00000000e+02, 1.00000000e+02,
        1.00000000e+02, 1.00000000e+02, 1.00000000e+02, 1.00000000e+02,
        1.00000000e+02, 1.00000000e+02, 1.00000000e+02, 1.00000000e+02,
        1.00000000e+02, 1.00000000e+02, 1.00000000e+02],
       [1.00000000e+02, 1.02020134e+02, 1.04081077e+02, 1.06183655e+02,
       

In [24]:
error = predicted_data-observed_data

NameError: name 'observed_data' is not defined

In [30]:
mse = (1/100) * np.sum((residual)**2)
mse

11.018077302529669

In [33]:
error = predicted_data-observed_data
error

NameError: name 'observed_data' is not defined